--- #YAML:1.3
name: CAE-Nastran-Nasmod
abstract: basic access to nastran models
version: 0.25
author:
  - Alexander Vogel <avoge@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.005
build_requires:
  Test: 0
resources:
  license: http://dev.perl.org/licenses/
keywords
  - CA
  - CAE
  - FEA
  - FEM
  - perl
  - nastran
  - Finite-Elements
  - CAE-Automation
  - CAE-Automatisierung
provides:
  CAE::Nastran::Nasmod:
    file: lib/CAE/Nastran/Nasmod.pm
    version: 0.25
  CAE::Nastran::Nasmod::Entity:
    file: lib/CAE/Nastran/Nasmod/Entity.pm
    version: 0.25
