  my $distmeta = {
    name => 'Nasmod',
    abstract => 'basic access to nastran models',
    description =>  "CAE::Nastran::Nasmod parses nastran models, "
      . "with an api it is possible to access or change certain data fields, "
      . "reduce data with a filter and write model to file",
    version  => '0.23',
    release_status => 'beta',
    author   => ['Alexander Vogel <avoge@cpan.org>'],
    license  => [ 'perl_5' ],
    no_index  => {
    	directory => ['spl/model.nas' ],
    },
    prereqs => {
      runtime => {
        requires => {
          'perl'   => '5.006',
        },
      },
      build => {
        requires => {
          'Test' => '0',
        },
      }
    },
    provides => {
    	'CAE::Nastran::Nasmod' => {
    		file => 'lib/CAE/Nastran/Nasmod.pm',
    		version => '0.23',
    	},
    	'CAE::Nastran::Nasmod::Entity' => {
    		file => 'lib/CAE/Nastran/Nasmod/Entity.pm',
    		version => '0.23',
    	},
    },
    resources => {
      license => ['http://dev.perl.org/licenses/'],
    },
    dynamic_config => 0,
    keywords => [ qw/ CA CAE FEA FEM Nastran Finite-Elements perl CAE-Automation CAE-Automatisierung / ],
    'meta-spec' => {
      version => '2',
      url     => 'https://metacpan.org/pod/CPAN::Meta::Spec',
    },
    generated_by => 'Module::Build version 0.36',
  };
 